// "use client";
// import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { AuthProvider } from "../context/store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SleekLoadingBar from "../components/SleekLoadingBar";
import Script from "next/script";

// import { baselightTheme } from "@/utils/theme/DefaultColors";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Codeswear - Wear the code",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" className="overflow-x-hidden">
        <head>
          <link rel="icon" href="/logo2.png" />
        </head>
        <body>
          <AuthProvider>
            <SleekLoadingBar />
            <Navbar />
            {children}
            <Footer />
            <ToastContainer
              theme="colored"
              autoClose={3000}
              position="top-left"
              bodyClassName="toastBody"
            />
          </AuthProvider>
        </body>
      </html>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </>
  );
}
